function createfigure1(X1, Y1, figure1)

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0 0 1 1]);
xlim([0 3.5])
ylim([0 3.5])
%%
hold(axes1,'all');

% Create rectangle
annotation(figure1,'rectangle',...
    [4/7 0 3/7 3/7],...
    'LineWidth',1,...
    'FaceColor',[0 0 0]);


% Create rectangle
annotation(figure1,'rectangle',...
    [4/7 4/7 3/7 3/7],...
    'LineWidth',1,...
    'FaceColor',[0 0 0]);

% Create rectangle
annotation(figure1,'rectangle',...
    [0 4/7 3/7 3/7],...
    'LineWidth',1,...
    'FaceColor',[0 0 0]);

% Create rectangle
annotation(figure1,'rectangle',...
    [0 0 3/7 3/7],...
    'LineWidth',1,...
    'FaceColor',[0 0 0]);


hold off

